services:
  db:
    image: postgres:15
    environment:
      # POSTGRES_USER: postgres (default)
      # POSTGRES_DB: postgres (default)
      POSTGRES_PASSWORD: test
    ports:
      - 5433:5432 # from host: postgresql://postgres:test@localhost:5433/postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Login Info
  # System: PostgresSQL,
  # Server: db,
  # Username: postgres
  # Password: test
  # Database: postgres
  adminer:
    image: adminer
    ports:
      - 8081:8080 # from host: localhost:8081
    depends_on:
      - db
