services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pg
      POSTGRES_DB: pg
      POSTGRES_PASSWORD: pg
    ports:
      - 5433:5432 # from host: postgresql://pg:pg@localhost:5433/pg
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Login Info
  # System: PostgresSQL,
  # Server: db,
  # Username/Password/Database: pg
  adminer:
    image: adminer
    ports:
      - 8081:8080 # from host: localhost:8081
    depends_on:
      - db
